### ISSUE TITLE
Solución incorrecta

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#1]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/c350f5a4f70bf0980211fa9b9184dbe54b81720f/Unit2/Exercise4.4.1/src/exercise_4_4_1.java#L1-L67

**Comment by Ainhoaleft** [comment]
Vaya, lo intentaré hacerlo mejor
