### ISSUE TITLE
Exercises Unit4

### ISSUE THREAD

**Issue by Ainhoaleft** [Ainhoaleft/DATA_ACCESS_AIA_2122#11]
Hola @jrgs he hecho los ejercicios 2.4 y la verdad no se si los tengo bien porque hice las tablas aparte por si fallaba algo y no lo ejecuté por eso y no sé si tengo que hacer inserts aunque me imagino que si alguna tabla tiene herencia y por otra parte no entiendo que hace cada cosa como por ejemplo el composite types, y el ejercicio db40 lo tengo a medias porque estoy mirando ejemplos y una pregunta ¿tengo que hacer 4 clases?

**Comment by jrgs** [comment]
Uf, muchas dudas y todas juntas..¿Puedes poner las dudas por el foro de la asignatura y, si es posible, un punto para cada una -con viñetas o algo así-?
Un saludo

**Comment by Ainhoaleft** [comment]
Vale ya te lo puesto en el foro, 
Un saludo.
