### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#12]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/89b5df201e721588817f228d979adb1e08e33cda/Unit4/Exercise%202.4.2/2.4.2.sql#L1

No deberías hacer un enum con este campo, los nombres en general son valores no limitables.

**Comment by Ainhoaleft** [comment]
👍
