### ISSUE TITLE
Domains

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#13]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/89b5df201e721588817f228d979adb1e08e33cda/Unit4/Exercise%202.4.2/2.4.2.sql#L27-L29

Estos tres campos deberían tener domains asociados

**Comment by Ainhoaleft** [comment]
en el email también?

**Comment by jrgs** [comment]
Si, claro
