### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#15]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/89b5df201e721588817f228d979adb1e08e33cda/Unit4/Exercise%202.4.2/2.4.2.sql#L22

El nombre del dominio es el mismo que el del campo, puede dar problemas, mejor añadir un prefijo: TYPE_SCORE

**Comment by Ainhoaleft** [comment]
👍 lo tendré en cuenta
