### ISSUE TITLE
domain name

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#17]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/89b5df201e721588817f228d979adb1e08e33cda/Unit4/Exercise%202.4.1/2.4.1.sql#L1

El nombre del dominio es poco descriptivo, mejor usar DPT_NAME, por ejemplo

**Comment by Ainhoaleft** [comment]
👍
