### ISSUE TITLE
¿?

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#2]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/c350f5a4f70bf0980211fa9b9184dbe54b81720f/Unit2/Exercise4.4.4/src/exercise_4_4_4.java#L16-L18

¿Un JFileChooser en una aplicación de consola?

**Comment by Ainhoaleft** [comment]
Lo mismo que lo anterior jaja, arreglado
