### ISSUE TITLE
path---route?

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#3]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/c350f5a4f70bf0980211fa9b9184dbe54b81720f/Unit2/Exercise4.4.4/src/exercise_4_4_4.java#L24-L25

**Comment by Ainhoaleft** [comment]
Que lo copie de internet y no me di cuenta, ya está arreglado
