### ISSUE TITLE
Muy bien

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#4]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/c350f5a4f70bf0980211fa9b9184dbe54b81720f/Unit2/Exercise6.1.1/src/ContactList.java#L4-L26

Yo no lo hubiera hecho mejor.

**Comment by Ainhoaleft** [comment]
Gracias :)
