### ISSUE TITLE
¿¿ ??

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#5]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/c350f5a4f70bf0980211fa9b9184dbe54b81720f/Unit2/Exercise7.2.1/src/UserParserHandler.java#L20-L100

¿De donde has sacado este código? Este ejercicio era copiar / pegar el código de los apuntes y hacerle una ligera modificación

**Comment by Ainhoaleft** [comment]
Ya lo he arreglado, copiando del pdf jaja
