### ISSUE TITLE
SQL

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#6]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/08dcecbf919f03021ffcdf5e7ac407e990e0b632/Unit3/Exercise7.4.1/src/main/java/com/aia2122/unit3/App.java#L21

En estos tres ejercicios necesito la consulta SQL, la puedes generar con la opción SCRIPT/CREATE SCRIPT y adjuntarla en un fichero de texto.

**Comment by Ainhoaleft** [comment]
Hecho
