### ISSUE TITLE
Extra job

### ISSUE THREAD

**Issue by jrgs** [Ainhoaleft/DATA_ACCESS_AIA_2122#7]
https://github.com/Ainhoaleft/DATA_ACCESS_AIA_2122/blob/08dcecbf919f03021ffcdf5e7ac407e990e0b632/Unit3/Exercise4.3.3/src/main/java/com/aia2122/unit3/App.java#L36

There was no need to insert data into the new field ;)

**Comment by Ainhoaleft** [comment]
👌
